package com.data.collection.data.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHECK_POINT".
*/
public class CheckPointDao extends AbstractDao<CheckPoint, Long> {

    public static final String TABLENAME = "CHECK_POINT";

    /**
     * Properties of entity CheckPoint.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Pointid = new Property(1, Long.class, "pointid", false, "POINTID");
        public final static Property Time = new Property(2, String.class, "time", false, "TIME");
        public final static Property Reporter = new Property(3, String.class, "reporter", false, "REPORTER");
        public final static Property Check = new Property(4, String.class, "check", false, "CHECK");
    }


    public CheckPointDao(DaoConfig config) {
        super(config);
    }
    
    public CheckPointDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHECK_POINT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"POINTID\" INTEGER NOT NULL ," + // 1: pointid
                "\"TIME\" TEXT UNIQUE ," + // 2: time
                "\"REPORTER\" TEXT," + // 3: reporter
                "\"CHECK\" TEXT);"); // 4: check
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHECK_POINT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CheckPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPointid());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String reporter = entity.getReporter();
        if (reporter != null) {
            stmt.bindString(4, reporter);
        }
 
        String check = entity.getCheck();
        if (check != null) {
            stmt.bindString(5, check);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CheckPoint entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getPointid());
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(3, time);
        }
 
        String reporter = entity.getReporter();
        if (reporter != null) {
            stmt.bindString(4, reporter);
        }
 
        String check = entity.getCheck();
        if (check != null) {
            stmt.bindString(5, check);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public CheckPoint readEntity(Cursor cursor, int offset) {
        CheckPoint entity = new CheckPoint( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // pointid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // time
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // reporter
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // check
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CheckPoint entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPointid(cursor.getLong(offset + 1));
        entity.setTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setReporter(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCheck(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CheckPoint entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CheckPoint entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CheckPoint entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
