package com.data.collection.data.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.data.collection.data.greendao.CheckPoint;
import com.data.collection.data.greendao.GatherPoint;
import com.data.collection.data.greendao.MessageRecord;
import com.data.collection.data.greendao.Sample;

import com.data.collection.data.greendao.CheckPointDao;
import com.data.collection.data.greendao.GatherPointDao;
import com.data.collection.data.greendao.MessageRecordDao;
import com.data.collection.data.greendao.SampleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig checkPointDaoConfig;
    private final DaoConfig gatherPointDaoConfig;
    private final DaoConfig messageRecordDaoConfig;
    private final DaoConfig sampleDaoConfig;

    private final CheckPointDao checkPointDao;
    private final GatherPointDao gatherPointDao;
    private final MessageRecordDao messageRecordDao;
    private final SampleDao sampleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        checkPointDaoConfig = daoConfigMap.get(CheckPointDao.class).clone();
        checkPointDaoConfig.initIdentityScope(type);

        gatherPointDaoConfig = daoConfigMap.get(GatherPointDao.class).clone();
        gatherPointDaoConfig.initIdentityScope(type);

        messageRecordDaoConfig = daoConfigMap.get(MessageRecordDao.class).clone();
        messageRecordDaoConfig.initIdentityScope(type);

        sampleDaoConfig = daoConfigMap.get(SampleDao.class).clone();
        sampleDaoConfig.initIdentityScope(type);

        checkPointDao = new CheckPointDao(checkPointDaoConfig, this);
        gatherPointDao = new GatherPointDao(gatherPointDaoConfig, this);
        messageRecordDao = new MessageRecordDao(messageRecordDaoConfig, this);
        sampleDao = new SampleDao(sampleDaoConfig, this);

        registerDao(CheckPoint.class, checkPointDao);
        registerDao(GatherPoint.class, gatherPointDao);
        registerDao(MessageRecord.class, messageRecordDao);
        registerDao(Sample.class, sampleDao);
    }
    
    public void clear() {
        checkPointDaoConfig.clearIdentityScope();
        gatherPointDaoConfig.clearIdentityScope();
        messageRecordDaoConfig.clearIdentityScope();
        sampleDaoConfig.clearIdentityScope();
    }

    public CheckPointDao getCheckPointDao() {
        return checkPointDao;
    }

    public GatherPointDao getGatherPointDao() {
        return gatherPointDao;
    }

    public MessageRecordDao getMessageRecordDao() {
        return messageRecordDao;
    }

    public SampleDao getSampleDao() {
        return sampleDao;
    }

}
